### ISSUE TITLE
500 error when balance field is not filled in on edit balance sheet

### ISSUE THREAD

**Issue by bbengfort** [bbengfort/ledger#51]
If the balance field is not filled in on the edit balance sheet a 500 error occurs as below:

Solution - make the field required so that you cannot submit the form without a number. Other JavaScript validation may be required. 

```
Internal Server Error: /api/sheets/2019-08-01/balances/

TypeError at /api/sheets/2019-08-01/balances/
Got a `TypeError` when calling `Balance.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `Balance.objects.create()`. You may need to make the field read-only, or override the BalanceSerializer.create() method to handle this correctly.
Original exception was:
 Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/serializers.py", line 932, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/base.py", line 766, in save_base
    update_fields=update_fields,
  File "/app/.heroku/python/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/app/accounts/signals.py", line 58, in update_ending_balance
    instance.update_ending_balance()
  File "/app/accounts/models/balance.py", line 170, in update_ending_balance
    total += self.credit_amount(completed=False)  # will be negative
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'Internal Server Error: /api/sheets/2019-08-01/balances/

TypeError at /api/sheets/2019-08-01/balances/
Got a `TypeError` when calling `Balance.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `Balance.objects.create()`. You may need to make the field read-only, or override the BalanceSerializer.create() method to handle this correctly.
Original exception was:
 Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/serializers.py", line 932, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/base.py", line 766, in save_base
    update_fields=update_fields,
  File "/app/.heroku/python/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/app/accounts/signals.py", line 58, in update_ending_balance
    instance.update_ending_balance()
  File "/app/accounts/models/balance.py", line 170, in update_ending_balance
    total += self.credit_amount(completed=False)  # will be negative
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
```

**Comment by bbengfort** [comment]
Temporary solution: make the input required so that you get browser-level validation. However, 500 errors still occur with this form, for example when the balance already exists for the sheet. We should probably do better at handling this.
